FROM python:3.8

RUN apt-get update && \
    apt-get install python3-dev python3-pip -y

RUN apt install mariadb-client -y

COPY ./requirements.txt /home/requirements.txt
COPY ./test.txt /home/test.txt

WORKDIR /home

RUN pip3 install -r /home/requirements.txt

RUN useradd -ms /bin/bash user_container
